# if you've not got any categories in One Account to import, set this
# to an empty dictionary

mapping = {'Charity':'Expenses:Charity',
'Education':'Expenses:Education',
'Loan':'',
'Transfer':'',
'Kim income':'Salary (Spouse)',
'Rental income':'Income:Rental Income',
'Other income':'Income:Other Income',
'Interest payments':'Expenses:Interest:Mortgage Interest',
'Rent':'Expenses:Rent',
'Tax':'Expenses:Uncategorised',
'Contracting':'Income:Contracting',
'Misc':'Expenses:Miscellaneous',
'Expenses tax deductable':'Expenses:Business Expenses:Misc',
'Holiday':'Expenses:Holiday',
'Refunds':'Income:Refunds',
'Household':'Expenses:Household',
'Expenses montague rd':'Expenses:Montague Road',
'Books':'Expenses:Books',
'Health and Beauty':'Expenses:Health and Beauty',
'Art materials':'Expenses:Art Materials',
'Clothes':'Expenses:Clothes',
'Entertainment':'Expenses:Entertainment:Uncategorised',
'Expenses contracting':'Expenses:Reimbursable Expenses',
'Car':'Expenses:Car:Uncategorised',
'Travel':'Expenses:Public Transport',
'Phone':'Expenses:Utilities:Mobile Phone',
'bills':'Expenses:Utilities:Uncategorised',
'Gifts':'',
'Eating and drinking':'Expenses:Entertainment:Eating and drinking',
'Cash':'Expenses:Cash (unknown)',
'Groceries':'Expenses:Groceries',}
